"""test1

Revision ID: 3fac0d4e5521
Revises: f2a6b795f62a
Create Date: 2023-02-19 19:16:49.308339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fac0d4e5521'
down_revision = 'f2a6b795f62a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
