"""testing offline

Revision ID: f2a6b795f62a
Revises: 6922e7d1bf0b
Create Date: 2023-02-19 18:57:00.346611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a6b795f62a'
down_revision = '6922e7d1bf0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
