"""test5

Revision ID: f2dabee565ca
Revises: 
Create Date: 2023-02-19 20:26:20.659905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2dabee565ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(length=36), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_services_description'), 'cleaning_services', ['description'], unique=False)
    op.create_index(op.f('ix_cleaning_services_id'), 'cleaning_services', ['id'], unique=False)
    op.create_index(op.f('ix_cleaning_services_uuid'), 'cleaning_services', ['uuid'], unique=False)
    op.create_table('electrial_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(length=36), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electrial_services_description'), 'electrial_services', ['description'], unique=False)
    op.create_index(op.f('ix_electrial_services_id'), 'electrial_services', ['id'], unique=False)
    op.create_index(op.f('ix_electrial_services_uuid'), 'electrial_services', ['uuid'], unique=False)
    op.create_table('plumbing_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(length=36), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plumbing_services_description'), 'plumbing_services', ['description'], unique=False)
    op.create_index(op.f('ix_plumbing_services_id'), 'plumbing_services', ['id'], unique=False)
    op.create_index(op.f('ix_plumbing_services_uuid'), 'plumbing_services', ['uuid'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_plumbing_services_uuid'), table_name='plumbing_services')
    op.drop_index(op.f('ix_plumbing_services_id'), table_name='plumbing_services')
    op.drop_index(op.f('ix_plumbing_services_description'), table_name='plumbing_services')
    op.drop_table('plumbing_services')
    op.drop_index(op.f('ix_electrial_services_uuid'), table_name='electrial_services')
    op.drop_index(op.f('ix_electrial_services_id'), table_name='electrial_services')
    op.drop_index(op.f('ix_electrial_services_description'), table_name='electrial_services')
    op.drop_table('electrial_services')
    op.drop_index(op.f('ix_cleaning_services_uuid'), table_name='cleaning_services')
    op.drop_index(op.f('ix_cleaning_services_id'), table_name='cleaning_services')
    op.drop_index(op.f('ix_cleaning_services_description'), table_name='cleaning_services')
    op.drop_table('cleaning_services')
    # ### end Alembic commands ###
